### PR TITLE
Add clink completions for ADB

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
### Description
This is the completions for the [ADB](https://developer.android.com/studio/command-line/adb) tool (Android Debugging Bridge), which I've always felt were missing in the default completions alongside Cmder.  Useful for both Android/Java development and managing your android device.

Additionally completions for [scrcpy](https://github.com/Genymobile/scrcpy) is also added (an awesome tool that uses adb.exe for mirroring android devices screen and controlling them)

**Author is @goldie-lin**

### Compatibility

Works with both the original (old) and the new clink

### CODE REVIEW

**Comment by goldie-lin** [comment]
Got the mentioned notification here. I'm ok 👌 with this PRs and have no issue about my clink lua scripts to be included in others' repo. Just go ahead. 👍

**Comment by DRSDavidSoft** [comment]
> Some feedback before merging this PR:
> 1. Why do the lua script files define both an argmatcher and a separate match generator? Can they instead use the [Functions As Argument Options](https://chrisant996.github.io/clink/clink.html#argmatcher_functions) syntax in Clink, and define only an argmatcher?
> 2. What is the purpose for using `null_parser` in so many places? It seems like that may interfere with completions in the rest of the command line.
> 3. Can you update the Clink web links to point to the current repo, i.e. https://github.com/chrisant996/clink?

_Originally posted by @chrisant996 in https://github.com/vladimir-kotikov/clink-completions/issues/153#issuecomment-1215129190_


@chrisant996 I updated the web links to the current repo, I haven't written the lua scripts myself (the developer is @goldie-lin), I'm just comitting them to the completions repo, hence the old urls (I hadn't noticed them)

**Comment by goldie-lin** [comment]
Sorry, I am on a business trip, and wouldn't be available to answer the questions until mid September. 🙇‍♂️

I used to use these lua scripts on my work (with CMD or ConEmu); but, actually I haven't now and hadn't been working on Android development since I changed job about three years ago, so I may need more time to take a look in and re-investing these lua scripts... 😅 Last two years I just maintain it if I occasionally found new options in adb/fastboot/scrcpy's `--help` log (yes, I have saved `--help` log of each version of adb/fastboot/scrcpy). 

I'm not a lua expert, just let it works.
Need time to take a look into your questions 

However, if someone else interested on maintaining these lua scripts, I'm nevermind that you fork it to do it yourself.

**Comment by chrisant996** [comment]
Ok, thanks, @goldie-lin.

@DRSDavidSoft can you share the output from `adb --help`, `fastboot --help`, and/or `srcopy --help`?  That will probably enable me to figure out the answers to both questions on my own.

**Comment by DRSDavidSoft** [comment]
@chrisant996 Sure, I am also interested in helping with rewrites, I'm just not sure which method is best to implement clink completions

### ADB 
<details><summary>Click to expand</summary>
<pre>
global options:
 -a         listen on all network interfaces, not just localhost
 -d         use USB device (error if multiple devices connected)
 -e         use TCP/IP device (error if multiple TCP/IP devices available)
 -s SERIAL  use device with given serial (overrides $ANDROID_SERIAL)
 -t ID      use device with given transport id
 -H         name of adb server host [default=localhost]
 -P         port of adb server [default=5037]
 -L SOCKET  listen on given socket for adb server [default=tcp:localhost:5037]

general commands:
 devices [-l]             list connected devices (-l for long output)
 help                     show this help message
 version                  show version num

networking:
 connect HOST[:PORT]      connect to a device via TCP/IP [default port=5555]
 disconnect [HOST[:PORT]]
     disconnect from given TCP/IP device [default port=5555], or all
 pair HOST[:PORT] [PAIRING CODE]
     pair with a device for secure TCP/IP communication
 forward --list           list all forward socket connections
 forward [--no-rebind] LOCAL REMOTE
     forward socket connection using:
       tcp:<port> (<local> may be "tcp:0" to pick any open port)
       localabstract:<unix domain socket name>
       localreserved:<unix domain socket name>
       localfilesystem:<unix domain socket name>
       dev:<character device name>
       jdwp:<process pid> (remote only)
       vsock:<CID>:<port> (remote only)
       acceptfd:<fd> (listen only)
 forward --remove LOCAL   remove specific forward socket connection
 forward --remove-all     remove all forward socket connections
 ppp TTY [PARAMETER...]   run PPP over USB
 reverse --list           list all reverse socket connections from device
 reverse [--no-rebind] REMOTE LOCAL
     reverse socket connection using:
       tcp:<port> (<remote> may be "tcp:0" to pick any open port)
       localabstract:<unix domain socket name>
       localreserved:<unix domain socket name>
       localfilesystem:<unix domain socket name>
 reverse --remove REMOTE  remove specific reverse socket connection
 reverse --remove-all     remove all reverse socket connections from device
 mdns check               check if mdns discovery is available
 mdns services            list all discovered services

file transfer:
 push [--sync] [-z ALGORITHM] [-Z] LOCAL... REMOTE
     copy local files/directories to device
     --sync: only push files that are newer on the host than the device
     -n: dry run: push files to device without storing to the filesystem
     -z: enable compression with a specified algorithm (any, none, brotli)
     -Z: disable compression
 pull [-a] [-z ALGORITHM] [-Z] REMOTE... LOCAL
     copy files/dirs from device
     -a: preserve file timestamp and mode
     -z: enable compression with a specified algorithm (any, none, brotli)
     -Z: disable compression
 sync [-l] [-z ALGORITHM] [-Z] [all|data|odm|oem|product|system|system_ext|vendor]
     sync a local build from $ANDROID_PRODUCT_OUT to the device (default all)
     -n: dry run: push files to device without storing to the filesystem
     -l: list files that would be copied, but don't copy them
     -z: enable compression with a specified algorithm (any, none, brotli)
     -Z: disable compression

shell:
 shell [-e ESCAPE] [-n] [-Tt] [-x] [COMMAND...]
     run remote shell command (interactive shell if no command given)
     -e: choose escape character, or "none"; default '~'
     -n: don't read from stdin
     -T: disable pty allocation
     -t: allocate a pty if on a tty (-tt: force pty allocation)
     -x: disable remote exit codes and stdout/stderr separation
 emu COMMAND              run emulator console command

app installation (see also `adb shell cmd package help`):
 install [-lrtsdg] [--instant] PACKAGE
     push a single package to the device and install it
 install-multiple [-lrtsdpg] [--instant] PACKAGE...
     push multiple APKs to the device for a single package and install them
 install-multi-package [-lrtsdpg] [--instant] PACKAGE...
     push one or more packages to the device and install them atomically
     -r: replace existing application
     -t: allow test packages
     -d: allow version code downgrade (debuggable packages only)
     -p: partial application install (install-multiple only)
     -g: grant all runtime permissions
     --abi ABI: override platform's default ABI
     --instant: cause the app to be installed as an ephemeral install app
     --no-streaming: always push APK to device and invoke Package Manager as separate steps
     --streaming: force streaming APK directly into Package Manager
     --fastdeploy: use fast deploy
     --no-fastdeploy: prevent use of fast deploy
     --force-agent: force update of deployment agent when using fast deploy
     --date-check-agent: update deployment agent when local version is newer and using fast deploy
     --version-check-agent: update deployment agent when local version has different version code and using fast deploy
     (See also `adb shell pm help` for more options.)
 uninstall [-k] PACKAGE
     remove this app package from the device
     '-k': keep the data and cache directories

debugging:
 bugreport [PATH]
     write bugreport to given PATH [default=bugreport.zip];
     if PATH is a directory, the bug report is saved in that directory.
     devices that don't support zipped bug reports output to stdout.
 jdwp                     list pids of processes hosting a JDWP transport
 logcat                   show device log (logcat --help for more)

security:
 disable-verity           disable dm-verity checking on userdebug builds
 enable-verity            re-enable dm-verity checking on userdebug builds
 keygen FILE
     generate adb public/private key; private key stored in FILE,

scripting:
 wait-for[-TRANSPORT]-STATE...
     wait for device to be in a given state
     STATE: device, recovery, rescue, sideload, bootloader, or disconnect
     TRANSPORT: usb, local, or any [default=any]
 get-state                print offline | bootloader | device
 get-serialno             print <serial-number>
 get-devpath              print <device-path>
 remount [-R]
      remount partitions read-write. if a reboot is required, -R will
      will automatically reboot the device.
 reboot [bootloader|recovery|sideload|sideload-auto-reboot]
     reboot the device; defaults to booting system image but
     supports bootloader and recovery too. sideload reboots
     into recovery and automatically starts sideload mode,
     sideload-auto-reboot is the same but reboots after sideloading.
 sideload OTAPACKAGE      sideload the given full OTA package
 root                     restart adbd with root permissions
 unroot                   restart adbd without root permissions
 usb                      restart adbd listening on USB
 tcpip PORT               restart adbd listening on TCP on PORT

internal debugging:
 start-server             ensure that there is a server running
 kill-server              kill the server if it is running
 reconnect                kick connection from host side to force reconnect
 reconnect device         kick connection from device side to force reconnect
 reconnect offline        reset offline/unauthorized devices to force reconnect

environment variables:
 $ADB_TRACE
     comma-separated list of debug info to log:
     all,adb,sockets,packets,rwx,usb,sync,sysdeps,transport,jdwp
 $ADB_VENDOR_KEYS         colon-separated list of keys (files or directories)
 $ANDROID_SERIAL          serial number to connect to (see -s)
 $ANDROID_LOG_TAGS        tags to be used by logcat (see logcat --help)
 $ADB_LOCAL_TRANSPORT_MAX_PORT max emulator scan port (default 5585, 16 emus)
 $ADB_MDNS_AUTO_CONNECT   comma-separated list of mdns services to allow auto-connect (default adb-tls-connect)
</pre>
</details>

Reference: https://developer.android.com/studio/command-line/adb

### Fastboot
<details><summary>Click to expand</summary>
<pre>
usage: fastboot [OPTION...] COMMAND...

flashing:
 update ZIP                 Flash all partitions from an update.zip package.
 flashall                   Flash all partitions from $ANDROID_PRODUCT_OUT.
                            On A/B devices, flashed slot is set as active.
                            Secondary images may be flashed to inactive slot.
 flash PARTITION [FILENAME] Flash given partition, using the image from
                            $ANDROID_PRODUCT_OUT if no filename is given.

basics:
 devices [-l]               List devices in bootloader (-l: with device paths).
 getvar NAME                Display given bootloader variable.
 reboot [bootloader]        Reboot device.

locking/unlocking:
 flashing lock|unlock       Lock/unlock partitions for flashing
 flashing lock_critical|unlock_critical
                            Lock/unlock 'critical' bootloader partitions.
 flashing get_unlock_ability
                            Check whether unlocking is allowed (1) or not(0).

advanced:
 erase PARTITION            Erase a flash partition.
 format[:FS_TYPE[:SIZE]] PARTITION
                            Format a flash partition.
 set_active SLOT            Set the active slot.
 oem [COMMAND...]           Execute OEM-specific command.
 gsi wipe|disable           Wipe or disable a GSI installation (fastbootd only).
 wipe-super [SUPER_EMPTY]   Wipe the super partition. This will reset it to
                            contain an empty set of default dynamic partitions.
 create-logical-partition NAME SIZE
                            Create a logical partition with the given name and
                            size, in the super partition.
 delete-logical-partition NAME
                            Delete a logical partition with the given name.
 resize-logical-partition NAME SIZE
                            Change the size of the named logical partition.
 snapshot-update cancel     On devices that support snapshot-based updates, cancel
                            an in-progress update. This may make the device
                            unbootable until it is reflashed.
 snapshot-update merge      On devices that support snapshot-based updates, finish
                            an in-progress update if it is in the "merging"
                            phase.
 fetch PARTITION OUT_FILE   Fetch a partition image from the device.
boot image:
 boot KERNEL [RAMDISK [SECOND]]
                            Download and boot kernel from RAM.
 flash:raw PARTITION KERNEL [RAMDISK [SECOND]]
                            Create boot image and flash it.
 --dtb DTB                  Specify path to DTB for boot image header version 2.
 --cmdline CMDLINE          Override kernel command line.
 --base ADDRESS             Set kernel base address (default: 0x10000000).
 --kernel-offset            Set kernel offset (default: 0x00008000).
 --ramdisk-offset           Set ramdisk offset (default: 0x01000000).
 --tags-offset              Set tags offset (default: 0x00000100).
 --dtb-offset               Set dtb offset (default: 0x01100000).
 --page-size BYTES          Set flash page size (default: 2048).
 --header-version VERSION   Set boot image header version.
 --os-version MAJOR[.MINOR[.PATCH]]
                            Set boot image OS version (default: 0.0.0).
 --os-patch-level YYYY-MM-DD
                            Set boot image OS security patch level.

Android Things:
 stage IN_FILE              Sends given file to stage for the next command.
 get_staged OUT_FILE        Writes data staged by the last command to a file.

options:
 -w                         Wipe userdata.
 -s SERIAL                  Specify a USB device.
 -s tcp|udp:HOST[:PORT]     Specify a network device.
 -S SIZE[K|M|G]             Break into sparse files no larger than SIZE.
 --force                    Force a flash operation that may be unsafe.
 --slot SLOT                Use SLOT; 'all' for both slots, 'other' for
                            non-current slot (default: current active slot).
 --set-active[=SLOT]        Sets the active slot before rebooting.
 --skip-secondary           Don't flash secondary slots in flashall/update.
 --skip-reboot              Don't reboot device after flashing.
 --disable-verity           Sets disable-verity when flashing vbmeta.
 --disable-verification     Sets disable-verification when flashing vbmeta.
 --fs-options=OPTION[,OPTION]
                            Enable filesystem features. OPTION supports casefold, projid, compress
 --unbuffered               Don't buffer input or output.
 --verbose, -v              Verbose output.
 --version                  Display version.
 --help, -h                 Show this message.
</pre>
</details>

Reference: https://helpmanual.io/help/fastboot/


### Scrcpy
<details><summary>Click to expand</summary>
<pre>
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
Usage: scrcpy [options]

Options:

    --always-on-top
        Make scrcpy window always on top (above other windows).

    -b, --bit-rate=value
        Encode the video at the gitven bit-rate, expressed in bits/s. Unit suffixes are supported: 'K' (x1000) and 'M' (x1000000).
        Default is 8000000.

    --codec-options=key[:type]=value[,...]
        Set a list of comma-separated key:type=value options for the device encoder.
        The possible values for 'type' are 'int' (default), 'long', 'float' and 'string'.
        The list of possible codec options is available in the Android documentation:
        <https://d.android.com/reference/android/media/MediaFormat>

    --crop=width:height:x:y
        Crop the device screen on the server.
        The values are expressed in the device natural orientation (typically, portrait for a phone, landscape for a tablet). Any
        --max-size value is computed on the cropped size.

    -d, --select-usb
        Use USB device (if there is exactly one, like adb -d).
        Also see -e (--select-tcpip).

    --disable-screensaver
        Disable screensaver while scrcpy is running.

    --display=id
        Specify the display id to mirror.
        The list of possible display ids can be listed by:
            adb shell dumpsys display
        (search "mDisplayId=" in the output)
        Default is 0.

    --display-buffer=ms
        Add a buffering delay (in milliseconds) before displaying. This increases latency to compensate for jitter.
        Default is 0 (no buffering).

    -e, --select-tcpip
        Use TCP/IP device (if there is exactly one, like adb -e).
        Also see -d (--select-usb).

    --encoder=name
        Use a specific MediaCodec encoder (must be a H.264 encoder).

    --force-adb-forward
        Do not attempt to use "adb reverse" to connect to the device.

    --forward-all-clicks
        By default, right-click triggers BACK (or POWER on) and middle-click triggers HOME. This option disables these shortcuts and
        forwards the clicks to the device instead.

    -f, --fullscreen
        Start in fullscreen.

    -K, --hid-keyboard
        Simulate a physical keyboard by using HID over AOAv2.
        It provides a better experience for IME users, and allows to generate non-ASCII characters, contrary to the default injection
        method.
        It may only work over USB.
        The keyboard layout must be configured (once and for all) on the device, via Settings -> System -> Languages and input ->
        Physical keyboard. This settings page can be started directly: `adb shell am start -a
        android.settings.HARD_KEYBOARD_SETTINGS`.
        However, the option is only available when the HID keyboard is enabled (or a physical keyboard is connected).
        Also see --hid-mouse.

    -h, --help
        Print this help.

    --legacy-paste
        Inject computer clipboard text as a sequence of key events on Ctrl+v (like MOD+Shift+v).
        This is a workaround for some devices not behaving as expected when setting the device clipboard programmatically.

    --lock-video-orientation[=value]
        Lock video orientation to value.
        Possible values are "unlocked", "initial" (locked to the initial orientation), 0, 1, 2 and 3. Natural device orientation is
        0, and each increment adds a 90 degrees rotation counterclockwise.
        Default is "unlocked".
        Passing the option without argument is equivalent to passing "initial".

    --max-fps=value
        Limit the frame rate of screen capture (officially supported since Android 10, but may work on earlier versions).

    -M, --hid-mouse
        Simulate a physical mouse by using HID over AOAv2.
        In this mode, the computer mouse is captured to control the device directly (relative mouse mode).
        LAlt, LSuper or RSuper toggle the capture mode, to give control of the mouse back to the computer.
        It may only work over USB.
        Also see --hid-keyboard.

    -m, --max-size=value
        Limit both the width and height of the video to value. The other dimension is computed so that the device aspect-ratio is
        preserved.
        Default is 0 (unlimited).

    --no-cleanup
        By default, scrcpy removes the server binary from the device and restores the device state (show touches, stay awake and
        power mode) on exit.
        This option disables this cleanup.

    --no-clipboard-autosync
        By default, scrcpy automatically synchronizes the computer clipboard to the device clipboard before injecting Ctrl+v, and the
        device clipboard to the computer clipboard whenever it changes.
        This option disables this automatic synchronization.

    --no-downsize-on-error
        By default, on MediaCodec error, scrcpy automatically tries again with a lower definition.
        This option disables this behavior.

    -n, --no-control
        Disable device control (mirror the device in read-only).

    -N, --no-display
        Do not display device (only when screen recording or V4L2 sink is enabled).

    --no-key-repeat
        Do not forward repeated key events when a key is held down.

    --no-mipmaps
        If the renderer is OpenGL 3.0+ or OpenGL ES 2.0+, then mipmaps are automatically generated to improve downscaling quality.
        This option disables the generation of mipmaps.

    --no-power-on
        Do not power on the device on start.

    --otg
        Run in OTG mode: simulate physical keyboard and mouse, as if the computer keyboard and mouse were plugged directly to the
        device via an OTG cable.
        In this mode, adb (USB debugging) is not necessary, and mirroring is disabled.
        LAlt, LSuper or RSuper toggle the mouse capture mode, to give control of the mouse back to the computer.
        If any of --hid-keyboard or --hid-mouse is set, only enable keyboard or mouse respectively, otherwise enable both.
        It may only work over USB.
        See --hid-keyboard and --hid-mouse.

    -p, --port=port[:port]
        Set the TCP port (range) used by the client to listen.
        Default is 27183:27199.

    --power-off-on-close
        Turn the device screen off when closing scrcpy.

    --prefer-text
        Inject alpha characters and space as text events instead of key events.
        This avoids issues when combining multiple keys to enter a special character, but breaks the expected behavior of alpha keys
        in games (typically WASD).

    --print-fps
        Start FPS counter, to print framerate logs to the console. It can be started or stopped at any time with MOD+i.

    --push-target=path
        Set the target directory for pushing files to the device by drag & drop. It is passed as is to "adb push".
        Default is "/sdcard/Download/".

    --raw-key-events
        Inject key events for all input keys, and ignore text events.

    -r, --record=file.mp4
        Record screen to file.
        The format is determined by the --record-format option if set, or by the file extension (.mp4 or .mkv).

    --record-format=format
        Force recording format (either mp4 or mkv).

    --render-driver=name
        Request SDL to use the given render driver (this is just a hint).
        Supported names are currently "direct3d", "opengl", "opengles2", "opengles", "metal" and "software".
        <https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER>

    --rotation=value
        Set the initial display rotation.
        Possible values are 0, 1, 2 and 3. Each increment adds a 90 degrees rotation counterclockwise.

    -s, --serial=serial
        The device serial number. Mandatory only if several devices are connected to adb.

    --shortcut-mod=key[+...][,...]
        Specify the modifiers to use for scrcpy shortcuts.
        Possible keys are "lctrl", "rctrl", "lalt", "ralt", "lsuper" and "rsuper".
        A shortcut can consist in several keys, separated by '+'. Several shortcuts can be specified, separated by ','.
        For example, to use either LCtrl+LAlt or LSuper for scrcpy shortcuts, pass "lctrl+lalt,lsuper".
        Default is "lalt,lsuper" (left-Alt or left-Super).

    -S, --turn-screen-off
        Turn the device screen off immediately.

    -t, --show-touches
        Enable "show touches" on start, restore the initial value on exit.
        It only shows physical touches (not clicks from scrcpy).

    --tcpip[=ip[:port]]
        Configure and reconnect the device over TCP/IP.
        If a destination address is provided, then scrcpy connects to this address before starting. The device must listen on the
        given TCP port (default is 5555).
        If no destination address is provided, then scrcpy attempts to find the IP address of the current device (typically connected
        over USB), enables TCP/IP mode, then connects to this address before starting.

    --tunnel-host=ip
        Set the IP address of the adb tunnel to reach the scrcpy server. This option automatically enables --force-adb-forward.
        Default is localhost.

    --tunnel-port=port
        Set the TCP port of the adb tunnel to reach the scrcpy server. This option automatically enables --force-adb-forward.
        Default is 0 (not forced): the local port used for establishing the tunnel will be used.

    --v4l2-sink=/dev/videoN
        Output to v4l2loopback device.
        It requires to lock the video orientation (see --lock-video-orientation).
        This feature is only available on Linux.

    --v4l2-buffer=ms
        Add a buffering delay (in milliseconds) before pushing frames. This increases latency to compensate for jitter.
        This option is similar to --display-buffer, but specific to V4L2 sink.
        Default is 0 (no buffering).
        This option is only available on Linux.

    -V, --verbosity=value
        Set the log level (verbose, debug, info, warn or error).
        Default is info.

    -v, --version
        Print the version of scrcpy.

    -w, --stay-awake
        Keep the device on while scrcpy is running, when the device is plugged in.

    --window-borderless
        Disable window decorations (display borderless window).

    --window-title=text
        Set a custom window title.

    --window-x=value
        Set the initial window horizontal position.
        Default is "auto".

    --window-y=value
        Set the initial window vertical position.
        Default is "auto".

    --window-width=value
        Set the initial window width.
        Default is 0 (automatic).

    --window-height=value
        Set the initial window height.
        Default is 0 (automatic).

Shortcuts:

    In the following list, MOD is the shortcut modifier. By default, it's (left) Alt or (left) Super, but it can be configured by
    --shortcut-mod (see above).

    MOD+f
        Switch fullscreen mode

    MOD+Left
        Rotate display left

    MOD+Right
        Rotate display right

    MOD+g
        Resize window to 1:1 (pixel-perfect)

    MOD+w
    Double-click on black borders
        Resize window to remove black borders

    MOD+h
    Middle-click
        Click on HOME

    MOD+b
    MOD+Backspace
    Right-click (when screen is on)
        Click on BACK

    MOD+s
    4th-click
        Click on APP_SWITCH

    MOD+m
        Click on MENU

    MOD+Up
        Click on VOLUME_UP

    MOD+Down
        Click on VOLUME_DOWN

    MOD+p
        Click on POWER (turn screen on/off)

    Right-click (when screen is off)
        Power on

    MOD+o
        Turn device screen off (keep mirroring)

    MOD+Shift+o
        Turn device screen on

    MOD+r
        Rotate device screen

    MOD+n
    5th-click
        Expand notification panel

    MOD+Shift+n
        Collapse notification panel

    MOD+c
        Copy to clipboard (inject COPY keycode, Android >= 7 only)

    MOD+x
        Cut to clipboard (inject CUT keycode, Android >= 7 only)

    MOD+v
        Copy computer clipboard to device, then paste (inject PASTE keycode, Android >= 7 only)

    MOD+Shift+v
        Inject computer clipboard text as a sequence of key events

    MOD+i
        Enable/disable FPS counter (print frames/second in logs)

    Ctrl+click-and-move
        Pinch-to-zoom from the center of the screen

    Drag & drop APK file
        Install APK from computer

    Drag & drop non-APK file
        Push file to device (see --push-target)

Environment variables:

    ADB
        Path to adb executable

    ANDROID_SERIAL
        Device serial to use if no selector (-s, -d, -e or --tcpip=<addr>) is specified

    SCRCPY_ICON_PATH
        Path to the program icon

    SCRCPY_SERVER_PATH
        Path to the server binary

Exit status:

      0  Normal program termination
      1  Start failure
      2  Device disconnected while running
</pre>
</details>

Reference: https://manpages.ubuntu.com/manpages/impish/man1/scrcpy.1.html (the cli interface is same in Windows & Linux)

---

Note: These are highly useful tools, if you use an Android phone I suggest trying adb and [scrcpy](https://github.com/Genymobile/scrcpy) out, also the `scrcpy` maintainer provides Windows builds with the adb.exe tool directly from Google, so you can try it out on your machine if interested

https://github.com/Genymobile/scrcpy/releases/download/v1.24/scrcpy-win64-v1.24.zip

Other than that, please feel free to ask me any questions, I'd also like to help with testing out any rewrites.

**Comment by DRSDavidSoft** [comment]
P.S. Quick question; is it possible to get output of, let's say `adb devices` in order to use it as arguments in a command such as `adb disconnect <parameter>`?

I'm willing to write parsers for this in lua, I'm just not sure how clink completions work in genereal, so I need some stub functions in order to make a PR for features such as this.

**Comment by chrisant996** [comment]
> P.S. Quick question; is it possible to get output of, let's say `adb devices` in order to use it as arguments in a command such as `adb disconnect <parameter>`?

See the `io.popen()` Lua function and the "Functions As Argument Options" section in the Clink docs.

> I'm willing to write parsers for this in lua, I'm just not sure how clink completions work in genereal, so I need some stub functions in order to make a PR for features such as this.

It'll be pretty quick for me to update this stuff. Give me a day or two, and then you can try it out and suggest or contribute further enhancements.

My changes are queuing up in the `dev` branch, by the way.

**Comment by chrisant996** [comment]
I see; there's a ton of command and flags, and the docs are a bit sketchy.  I won't worry about trying to make the parsers complete right now, I just want to verify a couple implementation points before adding them.

**Comment by chrisant996** [comment]
Oh!  I see what the generators are trying to do.  Yeah they can and should simply be functions in the argmatcher, instead of using a generator.

E.g. right now a generator looks for `abd -t` and runs `adb devices -l` to generate matches.  But it won't catch for example `abd -otherflag -t`.  Doing something like the following is much simpler and also fully integrates into the argmatcher:

```lua
local function transport_id_matches(word)
    local f = io.popen('adb devices -l 2>nul')
    if f then
        local transport_id = {}
        for line in f:lines() do
            if line ~= 'List of devices attached' then
                table.insert(transport_id, line:match('^.*%s+transport_id:(%d+)%s*.*$'))
            end
        end
        f:close()
        return transport_id
    end
end

clink.argmatcher("adb"):addflags("-t"..transport_id_matches)
```

**Comment by chrisant996** [comment]
Oh, and now I see what null_parser is doing.

**Comment by chrisant996** [comment]
> P.S. Quick question; is it possible to get output of, let's say `adb devices` in order to use it as arguments in a command such as `adb disconnect <parameter>`?

This is exactly why to not use a generator.  By using a function as an argument option, you can just add the function in every spot where you want e.g. the list of devices.  Versus making complicated changes to the regex parser inside the generator.

An argmatcher in Clink is implemented as a generator.  And it has lots of complicated logic for parsing a command line into argument slots, and nesting into other parsers.  By using generators directly to produce completion matches, it takes on the responsibility of re-implementing the argmatcher parsing engine.  But by using a function as an argument option, it can simply return the list of matches, and let the argmatcher engine handle all of the parsing in a consistent manner.

**Pull request closed without merging**
